source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.rc1', '< 5.1'
gem 'sprockets'
gem 'sprockets-rails'
gem 'turbolinks', '~> 5.x' # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks

gem 'puma', '~> 3.0'
# gem 'redis', '~> 3.0' # Use Redis adapter to run Action Cable in production

gem 'haml-rails'
gem 'sass-rails'
gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'uglifier', '>= 1.3.0' # Use Uglifier as compressor for JavaScript assets

# gem 'bcrypt', '~> 3.1.7' # Use ActiveModel has_secure_password

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'listen', '~> 3.0.5'
  # gem 'web-console' # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  # gem 'capistrano-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
