# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a7d8c95486b3593ba338a488665dba7ee2b6b3340f8ac0df308754df9846ff0b68ba24d2ee7105b5c042440b2d2b7b3a99b9578fa99eabb8babaa328005662

test:
  secret_key_base: ba2f7f3df19fc2a67056afd328a4dcab47d5ae2bfb4e7ff923d0e9ae0245fe5c549a1b68d428f9717f27f75d8984b484d263cd2638a157b521f4bf1382151c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
